# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='suggestions.proto',
  package='suggestions',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11suggestions.proto\x12\x0bsuggestions\"#\n\x12SuggestionsRequest\x12\r\n\x05\x62ooks\x18\x01 \x01(\t\"*\n\x13SuggestionsResponse\x12\x13\n\x0bsuggestions\x18\x01 \x01(\t2i\n\x12SuggestionsService\x12S\n\x0eSaySuggestions\x12\x1f.suggestions.SuggestionsRequest\x1a .suggestions.SuggestionsResponseb\x06proto3'
)




_SUGGESTIONSREQUEST = _descriptor.Descriptor(
  name='SuggestionsRequest',
  full_name='suggestions.SuggestionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='suggestions.SuggestionsRequest.books', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=69,
)


_SUGGESTIONSRESPONSE = _descriptor.Descriptor(
  name='SuggestionsResponse',
  full_name='suggestions.SuggestionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggestions', full_name='suggestions.SuggestionsResponse.suggestions', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['SuggestionsRequest'] = _SUGGESTIONSREQUEST
DESCRIPTOR.message_types_by_name['SuggestionsResponse'] = _SUGGESTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuggestionsRequest = _reflection.GeneratedProtocolMessageType('SuggestionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUGGESTIONSREQUEST,
  '__module__' : 'suggestions_pb2'
  # @@protoc_insertion_point(class_scope:suggestions.SuggestionsRequest)
  })
_sym_db.RegisterMessage(SuggestionsRequest)

SuggestionsResponse = _reflection.GeneratedProtocolMessageType('SuggestionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUGGESTIONSRESPONSE,
  '__module__' : 'suggestions_pb2'
  # @@protoc_insertion_point(class_scope:suggestions.SuggestionsResponse)
  })
_sym_db.RegisterMessage(SuggestionsResponse)



_SUGGESTIONSSERVICE = _descriptor.ServiceDescriptor(
  name='SuggestionsService',
  full_name='suggestions.SuggestionsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaySuggestions',
    full_name='suggestions.SuggestionsService.SaySuggestions',
    index=0,
    containing_service=None,
    input_type=_SUGGESTIONSREQUEST,
    output_type=_SUGGESTIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUGGESTIONSSERVICE)

DESCRIPTOR.services_by_name['SuggestionsService'] = _SUGGESTIONSSERVICE

# @@protoc_insertion_point(module_scope)
