# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/suggestions/suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/suggestions/suggestions.proto\x12\x0bsuggestions\"o\n\x0bVectorClock\x12\x32\n\x05\x63lock\x18\x01 \x03(\x0b\x32#.suggestions.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"e\n\x12SuggestionsRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05\x62ooks\x18\x02 \x01(\t\x12.\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x18.suggestions.VectorClock\"i\n\x13SuggestionsResponse\x12\x13\n\x0bsuggestions\x18\x01 \x01(\t\x12.\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x18.suggestions.VectorClock\x12\r\n\x05\x65rror\x18\x03 \x01(\t2b\n\x12SuggestionsService\x12L\n\x07suggest\x12\x1f.suggestions.SuggestionsRequest\x1a .suggestions.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.suggestions.suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=55
  _globals['_VECTORCLOCK']._serialized_end=166
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=122
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=166
  _globals['_SUGGESTIONSREQUEST']._serialized_start=168
  _globals['_SUGGESTIONSREQUEST']._serialized_end=269
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=271
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=376
  _globals['_SUGGESTIONSSERVICE']._serialized_start=378
  _globals['_SUGGESTIONSSERVICE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
