"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VectorClock(google.protobuf.message.Message):
    """Message to represent a vector clock."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ClockEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CLOCK_FIELD_NUMBER: builtins.int
    @property
    def clock(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]:
        """A mapping from service identifiers (or process names) to their counter values."""

    def __init__(
        self,
        *,
        clock: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clock", b"clock"]) -> None: ...

global___VectorClock = VectorClock

@typing.final
class SuggestionsRequest(google.protobuf.message.Message):
    """Request message including order information and the current vector clock."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    BOOKS_FIELD_NUMBER: builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    """Unique OrderID generated by the orchestrator."""
    books: builtins.str
    """Input book data for generating suggestions."""
    @property
    def vector_clock(self) -> global___VectorClock:
        """Current vector clock from previous events."""

    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        books: builtins.str = ...,
        vector_clock: global___VectorClock | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["vector_clock", b"vector_clock"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["books", b"books", "order_id", b"order_id", "vector_clock", b"vector_clock"]) -> None: ...

global___SuggestionsRequest = SuggestionsRequest

@typing.final
class SuggestionsResponse(google.protobuf.message.Message):
    """Response message carrying the generated suggestions and updated vector clock."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUGGESTIONS_FIELD_NUMBER: builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    suggestions: builtins.str
    """Recommended books if the execution flow is successful."""
    error: builtins.str
    """Optional error message in case of a failure."""
    @property
    def vector_clock(self) -> global___VectorClock:
        """Updated vector clock after processing this request."""

    def __init__(
        self,
        *,
        suggestions: builtins.str = ...,
        vector_clock: global___VectorClock | None = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["vector_clock", b"vector_clock"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "suggestions", b"suggestions", "vector_clock", b"vector_clock"]) -> None: ...

global___SuggestionsResponse = SuggestionsResponse
