# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.utils/pb/fraud_detection/fraud_detection.proto\x12\x12\x66raud_verification\"\x98\x02\n\x0c\x46raudRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x03 \x01(\t\x12#\n\x1b\x63redit_card_expiration_date\x18\x04 \x01(\t\x12\x14\n\x0cuser_comment\x18\x05 \x01(\t\x12\x14\n\x0citems_length\x18\x06 \x01(\t\x12G\n\x0cvector_clock\x18\x07 \x03(\x0b\x32\x31.fraud_verification.FraudRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x9f\x01\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\t\x12H\n\x0cvector_clock\x18\x02 \x03(\x0b\x32\x32.fraud_verification.FraudResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32]\n\x0c\x46raudService\x12M\n\x06\x64\x65tect\x12 .fraud_verification.FraudRequest\x1a!.fraud_verification.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_FRAUDREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_FRAUDRESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_FRAUDRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_FRAUDREQUEST']._serialized_start=71
  _globals['_FRAUDREQUEST']._serialized_end=351
  _globals['_FRAUDREQUEST_VECTORCLOCKENTRY']._serialized_start=301
  _globals['_FRAUDREQUEST_VECTORCLOCKENTRY']._serialized_end=351
  _globals['_FRAUDRESPONSE']._serialized_start=354
  _globals['_FRAUDRESPONSE']._serialized_end=513
  _globals['_FRAUDRESPONSE_VECTORCLOCKENTRY']._serialized_start=301
  _globals['_FRAUDRESPONSE_VECTORCLOCKENTRY']._serialized_end=351
  _globals['_FRAUDSERVICE']._serialized_start=515
  _globals['_FRAUDSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
