# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\"\xa5\x01\n\x11QueueOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x39\n\x0cvector_clock\x18\x03 \x03(\x0b\x32#.QueueOrderRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"$\n\x12QueueOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2@\n\nOrderQueue\x12\x32\n\x07\x45nqueue\x12\x12.QueueOrderRequest\x1a\x13.QueueOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUEUEORDERREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_QUEUEORDERREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_QUEUEORDERREQUEST']._serialized_start=43
  _globals['_QUEUEORDERREQUEST']._serialized_end=208
  _globals['_QUEUEORDERREQUEST_VECTORCLOCKENTRY']._serialized_start=158
  _globals['_QUEUEORDERREQUEST_VECTORCLOCKENTRY']._serialized_end=208
  _globals['_QUEUEORDERRESPONSE']._serialized_start=210
  _globals['_QUEUEORDERRESPONSE']._serialized_end=246
  _globals['_ORDERQUEUE']._serialized_start=248
  _globals['_ORDERQUEUE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
