# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/transaction_verification/transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@utils/pb/transaction_verification/transaction_verification.proto\x12\x18transaction_verification\"\x94\x02\n\x12TransactionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x03 \x01(\t\x12#\n\x1b\x63redit_card_expiration_date\x18\x04 \x01(\t\x12\x14\n\x0citems_length\x18\x05 \x01(\t\x12S\n\x0cvector_clock\x18\x06 \x03(\x0b\x32=.transaction_verification.TransactionRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xb1\x01\n\x13TransactionResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\t\x12T\n\x0cvector_clock\x18\x02 \x03(\x0b\x32>.transaction_verification.TransactionResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32{\n\x12TransactionService\x12\x65\n\x06verify\x12,.transaction_verification.TransactionRequest\x1a-.transaction_verification.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.transaction_verification.transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_TRANSACTIONREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_TRANSACTIONRESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_TRANSACTIONRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_TRANSACTIONREQUEST']._serialized_start=95
  _globals['_TRANSACTIONREQUEST']._serialized_end=371
  _globals['_TRANSACTIONREQUEST_VECTORCLOCKENTRY']._serialized_start=321
  _globals['_TRANSACTIONREQUEST_VECTORCLOCKENTRY']._serialized_end=371
  _globals['_TRANSACTIONRESPONSE']._serialized_start=374
  _globals['_TRANSACTIONRESPONSE']._serialized_end=551
  _globals['_TRANSACTIONRESPONSE_VECTORCLOCKENTRY']._serialized_start=321
  _globals['_TRANSACTIONRESPONSE_VECTORCLOCKENTRY']._serialized_end=371
  _globals['_TRANSACTIONSERVICE']._serialized_start=553
  _globals['_TRANSACTIONSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
