"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TransactionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class VectorClockEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ORDER_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREDIT_CARD_NUMBER_FIELD_NUMBER: builtins.int
    CREDIT_CARD_EXPIRATION_DATE_FIELD_NUMBER: builtins.int
    ITEMS_LENGTH_FIELD_NUMBER: builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    """Unique OrderID from the orchestrator."""
    name: builtins.str
    credit_card_number: builtins.str
    credit_card_expiration_date: builtins.str
    items_length: builtins.str
    @property
    def vector_clock(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]:
        """Vector clock for event ordering."""

    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        name: builtins.str = ...,
        credit_card_number: builtins.str = ...,
        credit_card_expiration_date: builtins.str = ...,
        items_length: builtins.str = ...,
        vector_clock: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credit_card_expiration_date", b"credit_card_expiration_date", "credit_card_number", b"credit_card_number", "items_length", b"items_length", "name", b"name", "order_id", b"order_id", "vector_clock", b"vector_clock"]) -> None: ...

global___TransactionRequest = TransactionRequest

@typing.final
class TransactionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class VectorClockEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    IS_FRAUD_FIELD_NUMBER: builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: builtins.int
    is_fraud: builtins.str
    @property
    def vector_clock(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]: ...
    def __init__(
        self,
        *,
        is_fraud: builtins.str = ...,
        vector_clock: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_fraud", b"is_fraud", "vector_clock", b"vector_clock"]) -> None: ...

global___TransactionResponse = TransactionResponse
