# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\"\x16\n\x14\x45xecutorStartRequest\"\'\n\x15\x45xecutorStartResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2G\n\rOrderExecutor\x12\x36\n\x05Start\x12\x15.ExecutorStartRequest\x1a\x16.ExecutorStartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTORSTARTREQUEST']._serialized_start=48
  _globals['_EXECUTORSTARTREQUEST']._serialized_end=70
  _globals['_EXECUTORSTARTRESPONSE']._serialized_start=72
  _globals['_EXECUTORSTARTRESPONSE']._serialized_end=111
  _globals['_ORDEREXECUTOR']._serialized_start=113
  _globals['_ORDEREXECUTOR']._serialized_end=184
# @@protoc_insertion_point(module_scope)
