# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x08\x62ooks_db\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\".\n\rChangeRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x32\x88\x02\n\rBooksDatabase\x12\x35\n\x04Read\x12\x15.books_db.ReadRequest\x1a\x16.books_db.ReadResponse\x12\x38\n\x05Write\x12\x16.books_db.WriteRequest\x1a\x17.books_db.WriteResponse\x12\x42\n\x0e\x44\x65\x63rementStock\x12\x17.books_db.ChangeRequest\x1a\x17.books_db.WriteResponse\x12\x42\n\x0eIncrementStock\x12\x17.books_db.ChangeRequest\x1a\x17.books_db.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=34
  _globals['_READREQUEST']._serialized_end=62
  _globals['_READRESPONSE']._serialized_start=64
  _globals['_READRESPONSE']._serialized_end=93
  _globals['_WRITEREQUEST']._serialized_start=95
  _globals['_WRITEREQUEST']._serialized_end=143
  _globals['_WRITERESPONSE']._serialized_start=145
  _globals['_WRITERESPONSE']._serialized_end=177
  _globals['_CHANGEREQUEST']._serialized_start=179
  _globals['_CHANGEREQUEST']._serialized_end=225
  _globals['_BOOKSDATABASE']._serialized_start=228
  _globals['_BOOKSDATABASE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
