# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0cverification\x1a\x0c\x63ommon.proto\"T\n\x0bInitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x33\n\x13transaction_request\x18\x02 \x01(\x0b\x32\x16.common.AllInfoRequest2\x83\x02\n\x13VerificationService\x12;\n\x16\x43reditCardVerification\x12\x0f.common.Request\x1a\x10.common.Response\x12\x39\n\x14UserDataVerification\x12\x0f.common.Request\x1a\x10.common.Response\x12=\n\x10initVerification\x12\x1a.common.InitAllInfoRequest\x1a\r.common.Empty\x12\x35\n\x10\x42ookListNotEmtpy\x12\x0f.common.Request\x1a\x10.common.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=62
  _globals['_INITREQUEST']._serialized_end=146
  _globals['_VERIFICATIONSERVICE']._serialized_start=149
  _globals['_VERIFICATIONSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
